use prueba1

insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Equinox', 1989, 199, 3, 7, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Civil War, The', 2010, 69, 3, 2, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Farinelli: il castrato', 2000, 1211, 4, 2, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Member of the Wedding, The', 2002, 1227, 1, 14, 9);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Bourne Legacy, The', 2007, 234, 1, 12, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('In the City of Sylvia (En la ciudad de Sylvia)', 1999, 268, 5, 5, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Willow', 2007, 221, 1, 8, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Snow on Tha Bluff', 1998, 488, 3, 16, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('TerrorStorm: A History of Government-Sponsored Terrorism', 2011, 171, 1, 12, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Secret Admirer', 2012, 159, 1, 4, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Two Years at Sea', 2009, 1337, 1, 3, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Something Like Happiness (Stestí)', 2009, 843, 3, 3, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Thick-Walled Room, The (Kabe atsuki heya)', 2011, 72, 4, 11, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Gallipoli', 1993, 1261, 4, 5, 9);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Losers, The', 2005, 787, 5, 16, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Devil at 4 O''Clock, The', 2012, 151, 5, 16, 9);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Mindscape of Alan Moore, The', 2010, 1000, 5, 10, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Bikini Carwash Company, The', 2009, 1061, 3, 9, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Devil and Daniel Johnston, The', 1987, 745, 5, 10, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Descent, The', 2010, 699, 4, 17, 9);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('At Any Price', 2003, 584, 3, 2, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Shepherd of the Hills, The', 1998, 378, 5, 14, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Extraterrestrial (Extraterrestre)', 2001, 323, 3, 9, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Take Out', 1990, 1026, 4, 17, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('I Want to Look Like That Guy', 1993, 216, 5, 16, 9);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Action Jackson', 2010, 932, 2, 16, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('God''s Gun', 1965, 1035, 5, 4, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Charlie, the Lonesome Cougar', 2002, 378, 2, 15, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Zebrahead', 1995, 253, 5, 9, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Melinda and Melinda', 2011, 291, 5, 16, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Masterminds', 1999, 802, 3, 6, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Clouds of Sils Maria', 1999, 389, 5, 17, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Cairo Time', 2008, 849, 2, 6, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Krush Groove', 1996, 1354, 5, 7, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Son of Frankenstein', 2005, 1097, 1, 1, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Big Shot: Confessions of a Campus Bookie', 1989, 302, 4, 9, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Sky Crawlers, The (Sukai kurora)', 2010, 762, 1, 9, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Mummy: Tomb of the Dragon Emperor, The', 2001, 1239, 3, 13, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Ghost World', 1999, 1358, 2, 7, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Forest Warrior', 2002, 993, 3, 4, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Doctor Who: The Time of the Doctor', 2012, 1191, 3, 12, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Applause (Applaus)', 1986, 436, 2, 11, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Disaster L.A.', 1992, 428, 5, 16, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Test Pilot', 1998, 116, 3, 6, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Amy', 2011, 325, 4, 8, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Animals are Beautiful People', 2011, 561, 4, 12, 9);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Street of Shame (Akasen chitai)', 2002, 1295, 1, 2, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('King Solomon''s Mines', 1999, 440, 3, 5, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Muppet Musicians of Bremen, The', 1999, 1014, 2, 5, 9);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Sugarbaby', 1991, 809, 2, 7, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Bad Asses (Bad Ass 2)', 2006, 1060, 4, 15, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Animal', 2004, 1336, 5, 5, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('8 (8, the Play)', 2004, 126, 4, 8, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Yanco ', 2000, 822, 5, 16, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Ant Bully, The', 1996, 1233, 5, 12, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Stray Cat Rock: Sex Hunter (Nora-neko rokku: Sekkusu hanta)', 1987, 771, 5, 13, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Pacifier, The', 2000, 776, 1, 7, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Sessions, The (Surrogate, The)', 1995, 227, 3, 3, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Lili', 2011, 1259, 2, 3, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Out of the Clear Blue Sky', 2006, 788, 5, 8, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Adventures of Hajji Baba, The', 2004, 1174, 5, 8, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Oranges, The', 1993, 1087, 2, 17, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Appointment with Danger', 1996, 1039, 5, 6, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Premiers désirs', 1995, 1094, 1, 6, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Bill & Ted''s Bogus Journey', 2000, 656, 1, 9, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Battle Beyond the Stars', 1997, 695, 4, 9, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Richard III', 2010, 755, 1, 8, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Tall Tale', 2008, 276, 2, 12, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Suture', 2011, 861, 5, 16, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Drifting Clouds (Kauas pilvet karkaavat)', 2010, 469, 1, 11, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Cyclo (Xich lo)', 2010, 490, 1, 3, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Bajo la Sal (Under the Salt)', 2011, 176, 4, 15, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('President''s Man, The', 2001, 570, 3, 12, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('House of Yes, The', 2002, 1334, 1, 10, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Detour ', 1996, 651, 1, 16, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Rumble in Hong Kong (Nu jing cha) (Heroine, The)', 2006, 200, 4, 5, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Conversation, The', 2009, 303, 2, 8, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Little Giant, The', 1997, 404, 4, 4, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Upside Down: The Creation Records Story', 2009, 558, 5, 16, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Cargo', 2005, 1006, 2, 7, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Stranded', 2007, 347, 5, 3, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Class, The (Klass)', 2011, 911, 4, 6, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Stonehearst Asylum', 2004, 759, 1, 9, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Lilting', 1996, 911, 4, 10, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Comebacks, The', 1999, 767, 3, 12, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Mickey', 1995, 321, 5, 16, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Package, The', 2008, 110, 3, 10, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Out of Africa', 2002, 907, 3, 16, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Any Which Way You Can', 1991, 251, 4, 13, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('It Started with Eve', 1997, 65, 4, 17, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Attila', 1995, 386, 4, 7, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Low Life', 2004, 1091, 3, 4, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Dark Half, The', 1993, 189, 4, 5, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Herb & Dorothy', 1995, 469, 1, 1, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Spy Next Door, The', 2003, 1173, 3, 9, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Fitzgerald Family Christmas, The', 2012, 561, 2, 5, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Police Academy 4: Citizens on Patrol', 2006, 343, 1, 10, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Brother Rat', 1996, 156, 3, 8, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Last Stand, The', 1986, 149, 1, 7, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Caligula', 1999, 960, 4, 8, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Brooklyn Bridge', 2009, 158, 2, 14, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Guest, The', 1996, 590, 3, 7, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Come Sweet Death (Komm, süsser Tod)', 2009, 1138, 4, 15, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Bounty Hunters (Bail Enforcers)', 2011, 781, 4, 13, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('The Search for Santa Paws', 2012, 215, 1, 8, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Hijack That Went South, The (Kaappari)', 1998, 1243, 5, 10, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Blow', 2006, 68, 1, 3, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Any Day Now', 2004, 1341, 3, 6, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('City Streets', 2012, 1356, 4, 17, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Born Yesterday', 1987, 1053, 1, 13, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Wild Tales', 2007, 540, 1, 5, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Better Off Dead...', 1998, 708, 2, 11, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Eddie Izzard: Circle', 2002, 800, 4, 1, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Long Riders, The', 2008, 1070, 1, 13, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Cria! (Cría cuervos)', 2011, 77, 2, 14, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Looney, Looney, Looney Bugs Bunny Movie, The', 1998, 1316, 1, 14, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Hurt', 1995, 613, 5, 11, 9);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Trouble Every Day', 2008, 938, 2, 13, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Shaft', 1966, 300, 3, 13, 9);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Wonder Boys', 2011, 444, 4, 17, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Speaking of Sex', 1992, 1089, 1, 4, 9);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Careful', 1993, 528, 2, 13, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Alamo Bay', 1992, 606, 5, 16, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('One Day', 1997, 371, 5, 8, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Reef, The', 1994, 269, 2, 3, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Demon Seed', 1999, 1290, 3, 7, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Fifty-Fifty (a.k.a. Schizo) (Shiza)', 2005, 205, 2, 17, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Cool World', 1991, 831, 3, 13, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Alexandra (Aleksandra)', 2011, 889, 4, 1, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('貞子3D', 1996, 453, 5, 14, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Internship, The', 2006, 1173, 4, 8, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Redwood Highway', 2008, 454, 3, 8, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Guarding Tess', 1993, 911, 3, 13, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Olympia Part One: Festival of the Nations (Olympia 1. Teil - Fest der Völker)', 1953, 838, 1, 1, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Corporation, The', 2007, 1038, 5, 2, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Brazil: In the Shadow of the Stadiums', 1994, 826, 4, 5, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Project X', 2004, 188, 2, 12, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Fahrenheit 451', 1967, 598, 3, 13, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Three Coins in the Fountain', 1996, 348, 5, 13, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Double Hour, The (La doppia ora)', 1997, 194, 5, 1, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('If a Tree Falls: A Story of the Earth Liberation Front', 2004, 700, 3, 7, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Intimate Enemies (L''ennemi intime)', 2003, 873, 5, 16, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('The 39 Steps', 2005, 768, 2, 3, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Pat Garrett and Billy the Kid', 1969, 908, 4, 7, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Half of a Yellow Sun', 1989, 669, 3, 17, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Harem suare', 1997, 552, 1, 16, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Storyville', 2000, 286, 3, 2, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Go Get Some Rosemary (Daddy Longlegs)', 1998, 301, 1, 3, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Funeral Parade of Roses (Bara no sôretsu)', 2010, 1273, 2, 3, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Vision Quest', 2004, 93, 4, 11, 9);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Skippy', 2008, 970, 4, 7, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Windtalkers', 2009, 216, 3, 9, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Gator', 1993, 756, 2, 12, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Same Old Song (On connaît la chanson)', 2011, 460, 3, 8, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Professional Gun, A (Mercenary, The) (Mercenario, Il)', 2000, 717, 2, 12, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Duel', 2007, 109, 4, 12, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Absent-Minded Professor, The', 1988, 1273, 2, 2, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Science and Islam', 1986, 227, 1, 2, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Bonnie Scotland (Heroes of the Regiment)', 2005, 772, 5, 3, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Rise of the Zombies', 1992, 1041, 2, 11, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Mabel at the Wheel', 1993, 85, 1, 13, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('W.', 1992, 81, 2, 8, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('1939: Hollywood''s Greatest Year', 1993, 562, 2, 9, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Collateral', 2009, 980, 2, 16, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('You Are So Beautiful (Je vous trouve très beau)', 2001, 282, 3, 1, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Prisoner of Paradise', 2006, 929, 2, 5, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Man with the Golden Arm, The', 1997, 800, 1, 11, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Chosin ', 1995, 776, 1, 11, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Glass Web, The', 1996, 546, 1, 15, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Toolbox Murders', 2011, 1192, 5, 1, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Divo, Il', 2002, 489, 5, 6, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Taxi Blues', 2012, 702, 1, 10, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Easy Money (Snabba Cash)', 2006, 1134, 2, 12, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Persepolis', 1995, 682, 1, 16, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Grace of Monaco', 1999, 1306, 4, 5, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Altered States', 1993, 1076, 3, 10, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Late Marriage (Hatuna Meuheret)', 1992, 1091, 3, 8, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Double Jeopardy', 1995, 56, 4, 17, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('1900 (Novecento)', 1996, 244, 2, 7, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Kramer vs. Kramer', 1993, 1342, 4, 7, 9);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Remarkable Power', 2010, 937, 1, 11, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Begin Again', 1966, 273, 3, 7, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Bloody Sunday', 1997, 523, 3, 6, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Baran', 1994, 1207, 3, 9, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Honey (Miele)', 2009, 465, 2, 4, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Mr. 3000', 2004, 1230, 4, 16, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Polite People (Kurteist fólk)', 2009, 1164, 5, 2, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Life Before Her Eyes, The', 2006, 358, 4, 11, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('WUSA', 2012, 809, 3, 7, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Year Ago in Winter, A (Im Winter ein Jahr)', 2012, 536, 4, 14, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Lifeboat', 2006, 139, 1, 16, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Human Capital (Il capitale umano)', 1990, 808, 3, 1, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Paranoia', 2001, 676, 2, 1, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Bobby', 2009, 344, 2, 8, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Postcards From the Edge', 2004, 382, 2, 8, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Two Lovers', 1994, 55, 5, 13, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Privates on Parade', 2001, 272, 1, 6, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('About Face: Supermodels Then and Now', 1997, 225, 1, 7, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Won Ton Ton: The Dog Who Saved Hollywood', 1995, 850, 1, 15, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('London to Brighton', 2008, 192, 3, 16, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Kill a Rat', 1986, 1232, 3, 2, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Enter the Ninja (a.k.a. Ninja I)', 1996, 963, 5, 16, 9);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Outlaw', 2000, 1206, 1, 8, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Perfect Murder, A', 1995, 1128, 3, 4, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Quarry, The', 2002, 340, 2, 12, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Blind Date', 1992, 168, 1, 13, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Heaven & Earth', 1996, 1204, 2, 11, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('American Movie', 2012, 887, 5, 1, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Clash of the Titans', 1995, 1259, 2, 7, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('And Now... Ladies and Gentlemen...', 2001, 464, 4, 13, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('The Car', 1991, 942, 2, 8, 9);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', 2004, 840, 2, 4, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Mister Johnson', 2007, 576, 4, 8, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('WolfCop', 2003, 676, 2, 15, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Shadow Dancer, The (Shadows in the Sun)', 1992, 1202, 3, 6, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Battle of Britain, The (Why We Fight, 4)', 1993, 972, 2, 13, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Explorers', 2007, 1277, 1, 16, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Rage', 1999, 662, 1, 4, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Red Riding: 1974', 1979, 301, 3, 2, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Cinema Komunisto', 2005, 597, 3, 3, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Warlock: The Armageddon', 2006, 1206, 5, 4, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Niagara', 2004, 1048, 1, 10, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Möbius', 1990, 849, 4, 8, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Tango', 2006, 614, 2, 7, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Paramore Live, the Final Riot!', 2009, 1088, 5, 5, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Male and Female', 2007, 1119, 2, 9, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Kairat', 1985, 134, 3, 4, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Highlander', 2001, 619, 1, 2, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Spider Baby or, The Maddest Story Ever Told (Spider Baby)', 1994, 597, 3, 12, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('And So It Goes', 1993, 1147, 2, 13, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Penny Serenade', 1994, 1006, 3, 11, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Bully', 1972, 381, 1, 8, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Lust for Gold', 1998, 1282, 2, 5, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Advanced Style', 1999, 1092, 2, 17, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Everybody''s Fine', 2000, 57, 4, 9, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Bicentennial Man', 2008, 1082, 2, 13, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Atlantis, the Lost Continent', 2009, 126, 3, 6, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Glowing Stars', 2003, 1202, 2, 9, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Hustlers, The (Veijarit)', 1998, 829, 3, 6, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Wrong Man, The', 1999, 441, 1, 16, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Living Room of the Nation, The (Kansakunnan olohuone)', 1977, 338, 3, 10, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Friday the 13th Part VIII: Jason Takes Manhattan', 2006, 743, 5, 6, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Bishop''s Wife, The', 2000, 749, 2, 8, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('SOS - en segelsällskapsresa', 1970, 499, 1, 17, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Scenes from a Mall', 1992, 464, 1, 5, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Chronicle of a Disappearance', 1998, 723, 4, 11, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Manchurian Candidate, The', 1967, 887, 5, 17, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Any Given Sunday', 1994, 980, 3, 6, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Countdown to Zero', 2000, 939, 4, 3, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Pursuit of D.B. Cooper, The (a.k.a. Pursuit)', 1995, 1163, 5, 6, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Life and Death of Colonel Blimp, The', 1996, 564, 5, 5, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Violent Saturday', 2002, 166, 5, 2, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('War Game, The', 2001, 982, 1, 12, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Shaft in Africa', 2002, 451, 1, 15, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Razortooth', 1995, 937, 1, 15, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Winnie the Pooh', 2001, 619, 2, 14, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Knucklehead', 1999, 207, 2, 12, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Ewok Adventure, The (a.k.a. Caravan of Courage: An Ewok Adventure)', 1994, 401, 5, 12, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Dolemite', 1988, 447, 1, 12, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Mikado, The', 2001, 851, 4, 1, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('First Day of the Rest of Your Life, The (Le premier jour du reste de ta vie)', 2010, 1213, 2, 13, 9);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Zigeunerweisen (Tsigoineruwaizen)', 2009, 309, 4, 15, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Edmond', 2004, 502, 4, 2, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Disconnect', 1992, 680, 4, 3, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Intermission', 1993, 1038, 5, 2, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('The Snow Woman', 1967, 1329, 1, 14, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Hopscotch', 2006, 1230, 5, 15, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Titicut Follies', 2012, 533, 5, 14, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Wu Tang Master (Tian shi zhuang xie)', 1998, 845, 4, 10, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Barbie: A Perfect Christmas', 2011, 628, 2, 4, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Flood', 1994, 140, 4, 17, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('She Done Him Wrong', 2002, 1235, 2, 15, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Mulan', 2007, 890, 5, 6, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Punk Singer, The', 1985, 420, 5, 14, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Shaggy D.A., The', 2000, 471, 4, 2, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Innocence', 2004, 1032, 5, 15, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Unreal Dream: The Michael Morton Story, An', 2011, 91, 4, 2, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Million Dollar Mystery', 2012, 911, 4, 4, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Io Island (Iodo)', 1996, 817, 1, 5, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Primary', 2002, 864, 5, 1, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('They Might Be Giants', 1994, 226, 5, 9, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Aces: Iron Eagle III', 2012, 908, 4, 16, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Down in the Delta', 1993, 854, 4, 10, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Pretty Woman', 2010, 1099, 5, 9, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Reel Bad Arabs: How Hollywood Vilifies a People', 1997, 1190, 5, 8, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Stealing Harvard', 1995, 476, 3, 17, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Man Who Sued God, The', 2009, 1156, 2, 12, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Growth', 2003, 183, 2, 4, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Flipped', 2011, 1339, 4, 16, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Dot the I', 1993, 1020, 1, 10, 9);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Delivery Man', 2010, 1137, 3, 11, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Adversary, The (L''adversaire)', 2009, 842, 4, 2, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('John Rabe', 2003, 376, 1, 5, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Wild About Harry', 2007, 941, 2, 5, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Remington and the Curse of the Zombadings', 1966, 795, 1, 4, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Cabin Fever', 2009, 105, 2, 6, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('The Lone Wolf Spy Hunt', 2010, 540, 3, 1, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Davy Crockett, King of the Wild Frontier', 2007, 117, 4, 17, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Bollywood/Hollywood', 1994, 439, 1, 16, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Blood Wedding (Bodas de sangre)', 2010, 714, 5, 16, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Business of Being Born, The', 2002, 227, 5, 1, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('I-See-You.Com', 1996, 99, 5, 7, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Client 9: The Rise and Fall of Eliot Spitzer', 2000, 878, 2, 14, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Sting, The', 1998, 481, 5, 7, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('World of Kanako, The (Kawaki.)', 1992, 127, 2, 14, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Cyrano de Bergerac', 1988, 655, 4, 11, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Pleasure Garden, The', 1993, 327, 3, 16, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Winter Passing', 1999, 1238, 4, 13, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('See Heaven', 2013, 285, 3, 12, 8);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Leif', 1997, 907, 3, 12, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Operation Endgame', 2000, 1323, 4, 10, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('JFK: The Smoking Gun', 2009, 186, 3, 9, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Day the Earth Stood Still, The', 2003, 180, 1, 10, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Little Engine That Could, The', 1985, 1132, 4, 5, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Just Friends?', 2012, 1065, 3, 15, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Siegfried', 2008, 546, 2, 11, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Royal Scandal, A', 1992, 1184, 1, 13, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Aces ''N'' Eights', 2005, 264, 3, 9, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Machine Gun McCain (Gli intoccabili)', 2006, 467, 5, 9, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Rurouni Kenshin (Rurôni Kenshin: Meiji kenkaku roman tan)', 2012, 74, 1, 11, 9);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Bulletproof', 2000, 1272, 2, 11, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Let''s Get Lost', 2006, 706, 1, 9, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('H.M. Pulham, Esq.', 2009, 599, 4, 8, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Wolf Children (Okami kodomo no ame to yuki)', 1996, 709, 3, 6, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('International, The', 1987, 979, 1, 14, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('In Vanda''s Room (No Quarto da Vanda)', 1995, 482, 3, 7, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Fall of the Roman Empire, The', 2008, 373, 2, 15, 9);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Godzilla vs. Mechagodzilla II (Gojira VS Mekagojira)', 2004, 1327, 4, 17, 6);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Darkness', 2000, 591, 4, 14, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Joshua', 1997, 562, 1, 7, 2);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('A Husband of Round Trip', 2011, 1198, 1, 8, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Secret Beyond the Door', 2009, 555, 4, 13, 11);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Story of G.I. Joe', 1990, 748, 2, 5, 1);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Bogowie', 2006, 751, 5, 7, 9);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Last Witness, The', 1986, 1234, 3, 13, 9);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Flirtation Walk', 2007, 583, 1, 8, 9);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Devil Is a Woman, The', 1998, 965, 1, 4, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Transamerica', 2003, 634, 4, 14, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Man from Snowy River, The', 1999, 191, 2, 6, 7);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Lost in Thailand (Ren zai jiong tu zhi tai jiong)', 1993, 607, 4, 5, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Raise Your Voice', 1993, 122, 1, 13, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Sergeant, The', 1985, 518, 5, 16, 9);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Monte Carlo', 2003, 381, 3, 8, 3);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Broadway Bill', 2004, 988, 3, 5, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Death of the Incredible Hulk, The', 2012, 1352, 3, 12, 9);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Otakus in Love', 2001, 201, 2, 5, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Starry Eyes', 1994, 130, 3, 17, 10);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Dirty Money (Un flic)', 2002, 1061, 4, 12, 5);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Dhobi Ghat', 2010, 1353, 1, 15, 4);
insert into librosTb (tituloLibro, a_oLibro, numPaginas, idEditorial, idAutor, idGenero) values ('Dare', 2010, 633, 5, 10, 6);

select * from librosTb